version: '3'
services:
  web:
    build: ./
    command: bash -c 'sleep 5; python entry.py --port 8000 -c docker.yaml'
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=pixelhunter
      - POSTGRES_PASSWORD=pixelhunter
      - POSTGRES_DB=pixelhunter
